defaults: &defaults

development:
  token_authorization:
    name: "ana_authenticated_user"
    password: "@n@_user"
    token: "Basic YW5hX2F1dGhlbnRpY2F0ZWRfdXNlcjpAbkBfdXNlcg=="
  twillio:
    sid: "AC969f17cb864ec269d068d4e4ff32c397"
    auth: "f9ca79e8e38852c26e106876338bda2b"
    number: "+14692086400"
  <<: *defaults

production:
  token_authorization:
    name: "ana_authenticated_user"
    password: "@n@_user"
    token: "Basic YW5hX2F1dGhlbnRpY2F0ZWRfdXNlcjpAbkBfdXNlcg=="
  twillio:
    sid: "AC969f17cb864ec269d068d4e4ff32c397"
    auth: "f9ca79e8e38852c26e106876338bda2b"
    number: "+14692086400"
  <<: *defaults
